"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j&0)qhvr)26nu#@e^x3^o)f6s#0g12-v***u_otf!*8y8e-0ip"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LIVERELOAD_HOST = '127.0.0.1'
LIVERELOAD_PORT = 35729


# Application definition

INSTALLED_APPS = [
    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",

    # third party apps (exception)
    'livereload',
    #django apps
    "django.contrib.staticfiles",

    # third party apps
    "compressor",
    'auditlog',
    'weasyprint',

    # local apps
    "apps.home",
    "apps.accounts",

    "apps.students",
    "apps.teachers",

    "apps.lessons",
    "apps.lesson_types",
    "apps.fullcalendar",

    "apps.subscriptions",
    "apps.subscription_types",


    "apps.payments",

    "apps.reports",

    "apps.users",
    "apps.activity_logs",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # third party apps
    'livereload.middleware.LiveReloadScript',
    'auditlog.middleware.AuditlogMiddleware'
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

USE_I18N = True
USE_TZ = True
USE_L10N = True
# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = 'es-ES'
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
]

TIME_ZONE = "America/Caracas"

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = 'dist/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    ('node_modules', os.path.join(BASE_DIR, 'node_modules/')),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# compressor settings
COMPRESS_ROOT = BASE_DIR / 'static'
COMPRESS_ENABLED = True
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"


# Celery Configuration
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = 'cache'
CELERY_CACHE_BACKEND = 'memory'

CELERY_BEAT_SCHEDULE = {
    'auto-renew-subscriptions': {
        'task': 'apps.home.tasks.auto_renew_subscriptions',
        'schedule': crontab(hour=0, minute=0),  # Ejecuta a la medianoche
    },
}


AUDITLOG_USE_REQUEST_ID = True
AUDITLOG_EXTRA_DATA = True
AUDITLOG_DISABLE_ADOPTION = False