# Generated by Django 4.2.5 on 2023-10-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_activitylog_ip_address_remove_activitylog_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Primer Nombre"),
        ),
    ]
