# Generated by Django 4.2.5 on 2023-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_teacher_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_status",
            field=models.BooleanField(default=False, verbose_name="Lesson Status"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="cathedra",
            field=models.CharField(max_length=255, verbose_name="Cathedra"),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="modality",
            field=models.CharField(max_length=255, verbose_name="Modality"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="student",
            name="birthdate",
            field=models.DateField(verbose_name="Birthdate"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_surname",
            field=models.CharField(max_length=255, verbose_name="First Surname"),
        ),
        migrations.AlterField(
            model_name="student",
            name="identify_card",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identify Card"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="student",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Second Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="second_surname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Second Surname"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="auto_renewal",
            field=models.BooleanField(default=True, verbose_name="Auto Renewal"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="number_of_lessons",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of Lessons"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="address",
            field=models.TextField(verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="birthdate",
            field=models.DateField(verbose_name="Birthdate"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_surname",
            field=models.CharField(max_length=255, verbose_name="First Surname"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="identify_card",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identify Card"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Second Name"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="second_surname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Second Surname"
            ),
        ),
    ]
