# Generated by Django 4.2.5 on 2023-10-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_lesson_description_alter_lesson_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone"),
        ),
    ]
