# Generated by Django 4.2.5 on 2023-10-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_lesson_lesson_type_alter_lesson_subscription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_standard_finance", "Can view standard finance"),
                    ("view_advanced_finance", "Can view advanced finance"),
                ],
            },
        ),
    ]
