# Generated by Django 4.2.5 on 2023-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_financepermission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinancePermission",
        ),
    ]
