# Generated by Django 4.2.5 on 2023-10-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_remove_subscription_unique_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="identify_card",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Identify Card",
            ),
        ),
    ]
