# Generated by Django 4.2.5 on 2023-10-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("lesson_status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LessonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cathedra", models.CharField(max_length=255)),
                ("modality", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LessonXSubscriptionXTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identify_card",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                (
                    "second_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_surname", models.CharField(max_length=255)),
                (
                    "second_surname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birthdate", models.DateField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "subscription_status",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("number_of_lessons", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionXStudentXPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identify_card",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                (
                    "second_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_surname", models.CharField(max_length=255)),
                (
                    "second_surname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birthdate", models.DateField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=(
                    "identify_card",
                    "first_name",
                    "second_name",
                    "first_surname",
                    "second_surname",
                    "birthdate",
                ),
                name="unique_teacher",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionxstudentxpayment",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.payment"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionxstudentxpayment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.student"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionxstudentxpayment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptiontype",
            constraint=models.UniqueConstraint(
                fields=("name", "price"), name="unique_subscription_type"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="lessons",
            field=models.ManyToManyField(
                through="home.LessonXSubscriptionXTeacher", to="home.lesson"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="students",
            field=models.ManyToManyField(
                through="home.SubscriptionXStudentXPayment", to="home.student"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="type_subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.subscriptiontype"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subscriptions",
            field=models.ManyToManyField(
                through="home.SubscriptionXStudentXPayment", to="home.subscription"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscriptions",
            field=models.ManyToManyField(
                through="home.SubscriptionXStudentXPayment", to="home.subscription"
            ),
        ),
        migrations.AddField(
            model_name="lessonxsubscriptionxteacher",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.lesson"
            ),
        ),
        migrations.AddField(
            model_name="lessonxsubscriptionxteacher",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.subscription"
            ),
        ),
        migrations.AddField(
            model_name="lessonxsubscriptionxteacher",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.teacher"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessontype",
            constraint=models.UniqueConstraint(
                fields=("cathedra", "modality"), name="unique_lesson_type"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.lessontype"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subscriptions",
            field=models.ManyToManyField(
                through="home.LessonXSubscriptionXTeacher", to="home.subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=(
                    "identify_card",
                    "first_name",
                    "second_name",
                    "first_surname",
                    "second_surname",
                    "birthdate",
                ),
                name="unique_student",
            ),
        ),
    ]
