# Generated by Django 4.2.5 on 2023-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
