# Generated by Django 4.2.5 on 2023-10-22 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_payment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscription_status",
            new_name="is_active",
        ),
    ]
