# Generated by Django 4.2.5 on 2023-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_lesson_end_date_alter_lesson_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
