# Generated by Django 4.2.5 on 2023-10-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_subscription_lessons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionxstudentxpayment",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="subscriptionxstudentxpayment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="subscriptionxstudentxpayment",
            name="subscription",
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.teacher",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="LessonXSubscriptionXTeacher",
        ),
        migrations.DeleteModel(
            name="SubscriptionXStudentXPayment",
        ),
    ]
