# Generated by Django 4.2.5 on 2023-10-16 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_subscriptionxstudentxpayment_payment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="subscriptions",
            new_name="subscription",
        ),
    ]
