# Generated by Django 4.2.5 on 2023-10-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_lesson_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionxstudentxpayment",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.payment",
            ),
        ),
    ]
