# Generated by Django 4.2.5 on 2023-10-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_rename_subscription_status_subscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="auto_renewal",
            field=models.BooleanField(default=True),
        ),
    ]
