# Generated by Django 4.2.5 on 2023-10-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_subscription_auto_renewal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
