# Generated by Django 4.2.5 on 2023-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_subscriptions_lesson_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
