# Generated by Django 4.2.5 on 2023-10-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_lesson_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_status",
            field=models.BooleanField(default=False),
        ),
    ]
