# Generated by Django 4.2.5 on 2023-10-25 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0006_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="url",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
