# Generated by Django 4.2.5 on 2023-10-17 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_lesson_lesson_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="type_subscription",
            new_name="subscription_type",
        ),
    ]
