# Generated by Django 4.2.5 on 2023-10-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_student_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.lessontype",
                verbose_name="Lesson Type",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.teacher",
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="home.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.subscriptiontype",
                verbose_name="Subscription Type",
            ),
        ),
    ]
