# Generated by Django 4.2.5 on 2023-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_delete_financepermission"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("student",), name="unique_subscription"
            ),
        ),
    ]
